name: ASCII Art
on: push
jobs:
    art_work:
        name: Art Work
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setting Permissions
              run: chmod +x .github/workflows/ascii-script.sh

            - name: Executing shell script
              run: .github/workflows/ascii-script.sh

            - name: Show Art
              run: cat tux.txt