name: ASCII Art
on: push
jobs:
    art_work:
        name: Art Work
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
            
            - name: List files
              run: ls -ltra

            - name: Executing shell script
              run: ./ascii-script.sh

            - name: Show Art
              run: cat tux.txt