name: Generate ASCII Artwork
on: push
jobs:
    first-art:
        name: My First Art
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f tux "The T-virus is protean, changing from liquid to airborne to blood transmission, depending on its environment. It is almost impossible to kill." >> tux.txt

            - name: Test File Existence
<<<<<<< HEAD
              run: grep -i "virus" tux.txt
=======
              run: grep -i "virus" dragon.txt
>>>>>>> 4db82d463eb7fb2efa1ba2cfa51f1ddf080fc7f5

            - name: Read File
              run: cat tux.txt

            - name: List files
              run: ls -ltra