name: My First Workflow
on: push
jobs: 
    first-job:
        name: My First Job
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Welcome message
              run: echo " Hello Meenal, Let's learn DevOps Together!"

            - name: List files
              run: ls

            - name: Read the file
              run: cat README.md