name: Multiple Job Workflow
on: push
jobs:
    build_job1:
        name: Build Job
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f hellokitty "I'm Nano's cat" >> kitty.txt

            - name: Upload Kitty file
              uses: actions/upload-artifact@v4
              with:
                name: kitty-text-file
                path: kitty.txt

    test_job2:
        name: Test Job
        runs-on: ubuntu-latest
        needs: build_job1
        steps:
            - name: Download Kitty file
              uses: actions/download-artifact@v4
              with:
                name: kitty-text-file

            - name: Test file exists
              run: grep -i "cat" kitty.txt

    deploy_job3:
        name: Deploy Job
        runs-on: ubuntu-latest
        needs: test_job2
        steps:
            - name: Deploy
              run: echo Deploying ... .. .

