name: Cron Job Workflow
on:
    schedule:
        - cron: 1 * * * *
jobs:
    my-cron-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Execute the shell script
              run: |
                chmod +x ./fun-cron-script.sh
                ./fun-cron-script.sh
