name: Exploring Varibales and Secrets
on: push
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Build Docker image
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest

            - name: Docker login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME}} --password=${{ secrets.DOCKER_PASSWORD}}

            - name: Publish the Docker image
              run: echo docker push ${{ env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME}}/${{ env.IMAGE_NAME}}:latest
    

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest

            - name: Deploying
              run: echo "Deployed the Docker image"
       